project_id = "fypibednjongfztfjvbp"

[functions.track-visitor]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.trigger-event-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.validate-reset-token]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false